### PR TITLE
0.5b snapcast

### PR DESCRIPTION
**Pull request by colinleroy**
Hi !

I've worked on Snapcast integration and this is the result. I hope you'll like it. Make sure to tell me if you would like to see changes/fixes :)
I fiddled around and I think I got the hard part right (switching from MPD to Snapcast and back). It works quite well : https://www.youtube.com/watch?v=YHoX60xmFr8

### CODE REVIEW

**Comment by gearhead** [comment]
I'm going to need a bit of hand holding. I have pulled this to a local branch on my home device to check it out. In the UI, it says "Disabled, the required software is not installed on this model". What is it looking for? How do I install the snapcast components to get this working?

**Comment by colinleroy** [comment]
Hi!
You have to install the snapcast package that is available there: https://github.com/gearhead/RuneOS/blob/master/packages/snapcast/
1) download it to the device, either the snapcast-0.14.0-1-armv7h.pkg.tar.xz or armv6h depending on your device
2) install it using 
pacman -U snapcast-0.14.0-1-armv7h.pkg.tar.xz

(By the way, it has to be done on both devices)

Hope this helps!

**Comment by gearhead** [comment]
Ok. I have set up 2 devices with snapcast and have pointed my git to a local branch I call snaptest. Interestingly, on one machine, it seems to work. Took a long time to start up and show me the queue and library pages, though. I did the same thing on a second device. Installed snapserver.xz, switched to a local snaptest branch and rebooted. I went to settings and turned it on. Then I rebooted again. On this second device I get no snapcast chicklet on the Library page. 
If I start something playing on the second device, its stream will show up on the first machine and I can select it. I just cannot do this on the second one. Is there something I am missing?
On the second one, the server is definitely running:
Jan 29 13:16:26 runeaudio systemd[1]: Starting Snapcast server...
Jan 29 13:16:26 runeaudio snapserver[825]: daemon started
Jan 29 13:16:26 runeaudio systemd[1]: Started Snapcast server.

**Comment by colinleroy** [comment]
Hi,
You mean that on the second device, you don't even have the Snapcast button on the Library page ? This is strange. I'm re-reading the patch and realize I even forgot to add a condition on snapclient's presence to show the button : it should always be there as I added 'Snapcast' => $snapcast in runeaudio.php's ui_libraryHome(), with $snapcast set to 1.

I'll give it another look this evening I hope !

**Comment by gearhead** [comment]
That is correct. No snapcast button on the Library page but just on one of the devices.

**Comment by colinleroy** [comment]
I'll investigate that this evening, this is weird though. Can you double-check if there's no git strangeness on that device's branch checkout ? (using git status / git diff) ?

**Comment by gearhead** [comment]
I cannot get to 'home' right now, but as of yesterday, it was fine on both of them. If the internet comes back up, I'll edit this and see what it reports on both machines.
Machine that shows the 'snapsync' entry:
root@livingrune(rw):/var/www# git status
On branch snaptest
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/templates/header.php

no changes added to commit (use "git add" and/or "git commit -a")

The one that does not show 'snapsync':
root@runeaudio(rw):/var/www# git status
On branch snaptest
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/libs/runeaudio.php
        modified:   assets/js/runeui.js
        modified:   db/index.php

no changes added to commit (use "git add" and/or "git commit -a")

I do not know how they are different as I did a git pull rebooted then created the snaptest branch locally on both machines. I'll reset both machines and try it again.

**Comment by gearhead** [comment]
Update: on the machine that would not show 'snapcast' in the library, I blew away the full /var/www directory (rm -rf /var/www) and re-cloned 0.5b. I reset the other machine (that does show it) by deleting the local snaptest branch, rebooting and then creating a local branch then switching to it. When it rebooted, it all seems 'there' whereas the other clean install does not. even after I 
This one works:
```
root@livingrune(rw):/var/www# git pull
Already up to date.
root@livingrune(rw):/var/www# git fetch origin pull/11/head:snaptest
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Total 98 (delta 82), reused 83 (delta 82), pack-reused 15
Unpacking objects: 100% (98/98), done.
From https://github.com/gearhead/RuneUI
 * [new ref]         refs/pull/11/head -> snaptest
root@livingrune(rw):/var/www# git checkout snaptest
M       app/templates/header.php
Switched to branch 'snaptest'
root@livingrune(rw):/var/www# git status
On branch snaptest
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   app/templates/header.php

no changes added to commit (use "git add" and/or "git commit -a")
```
This one does not:
```
root@runeaudio(rw):/var/www# git pull
Already up to date.
root@runeaudio(rw):/var/www# git fetch origin pull/11/head:snaptest
remote: Enumerating objects: 83, done.
remote: Counting objects: 100% (83/83), done.
remote: Total 98 (delta 82), reused 83 (delta 82), pack-reused 15
Unpacking objects: 100% (98/98), done.
From https://github.com/gearhead/RuneUI
 * [new ref]         refs/pull/11/head -> snaptest
root@runeaudio(rw):/var/www#  git checkout snaptest
Switched to branch 'snaptest'
root@runeaudio(rw):/var/www# git status
On branch snaptest
nothing to commit, working tree clean
```
Even after copying over the header.php from the functional device and rebooting, still no 'snapcast' in the library.

**Comment by colinleroy** [comment]
Hi,
I'll do the same as you did, I hope to reproduce ! Normally, the Snapcast button is generated by runeui.js when the library websocket channel includes a"Snapcast => 1" json key.
Oh that makes me think, maybe the one where it doesn't work is in prod mode and includes runeui.min.js !
I didn't regenerate it because I don't know how to do so...

**Comment by colinleroy** [comment]
Yes, I think that's it, it's only available in Dev mode because I didn't re-minify runeui.js.

**Comment by gearhead** [comment]
please minify it and push the result.

**Comment by colinleroy** [comment]
Hi,
Can you tell me the minification procedure?

**Comment by gearhead** [comment]
that is not in my wheelhouse. I did a google on it and came across a web based one and a few applications.
https://javascript-minifier.com/
https://developers.google.com/speed/docs/insights/MinifyResources

**Comment by colinleroy** [comment]
I'll give it a look ASAP then :) 

But I'm wondering: is the added complexibility (and maintainability issue) worth the size gain ? runeui.js is 144kB, runeui.min.js is 80kB. The total page download is 2.0MB. 
Does it really matter, especially over the LAN?

If you think it doesn't, I can submit a separate pull request to drop the minified version.

**Comment by gearhead** [comment]
My concern is that the pull, as it is now, will only work with the dev
enabled. If it is to work with 'rune 0.5b' it really should work with
either /dev or /prod...

**Comment by colinleroy** [comment]
Hi!
I figured it out - it's with Grunt :) I've pushed the new minified runeui.min.js.

**Comment by colinleroy** [comment]
Hi,
Any status update on this pull request ? I'll have to fix newly appeared conflicts, but I'd like to know what you'd like to do with it :)

**Comment by gearhead** [comment]
Been sidetracked with other rune activities over the past couple weeks. My initial thought is that I'd rather use Shairport-sync to do multi room, because it is installed on all images and should be able to do what we need it to do. That said, all I have found is a nodeJS implementation of airplay_hub and node_airtunes:
https://github.com/lperrin/node_airtunes
https://github.com/noelhibbard/node-airplayhub

But that snapsync seems to work and you have implemented it in the UI, we will have to discuss it. Give me a few weeks to get these other tasks done and I'll get back on it.

**Comment by colinleroy** [comment]
Hi gearhead,
Thanks for the update :) I'll fix the pull request to address conflicts asap.

**Comment by colinleroy** [comment]
I remerged your branch :)

**Comment by colinleroy** [comment]
Hi,
Still hoping for a merge maybe ;)

**Pull request closed without merging**
