### PR TITLE
Two littles fixes

### PR DESCRIPTION
**Pull request by colinleroy**
Hi,
This patch fixes two things: 
1) close the redis connection before restarting rune_SY_wrk 
2) fix an infinite loop of "mpd version changed" in rune_SY_wrk when mpd version is not 0.20.20 (my case during work on an automated image builder)

Thanks!

### CODE REVIEW

**Comment by janui** [comment]
Hi colinroy,
I have retested the standard code. This is easy to do by setting the redis variable 'mpdconf version' back to 0.20.19, with 'redis-cli hset mpdconf version 0.20.19' then rebooting. The process does not loop, the value of  'mpdconf version' will be set to the actual MPD version by the routine wrk_mpdconf($redis,'reset').
Closing redis in the place where you suggest will prevent the above mentioned process from working correctly because $redis is passed as a variable (redis needs to be open at this point). Redis only needs explicitly closing when it will be reopened within the script, in this case the script exits by restarting itself. The redis handle will then automatically be recycled.
janui

**Comment by colinleroy** [comment]
Hi,
Thanks. Maybe my problem came from something else !

**Comment by colinleroy** [comment]
I confirm the problem though. You can test it, instead of using "redis-cli hset mpdconf version 0.20.19", by changing the 0.20.20 in the code to something else. Because when mpd version has changed, everything is reset and Rune still expects the version defined in the code:

Here is the log file:
```
--------------- start: rune_SY_wrk.php ---------------
[09-Feb-2019 15:37:49 UTC] ### sysCmd($str) ###  echo "--------------- start: rune_SY_wrk.php ---------------" > /var/log/runeaudio/rune_SY_wrk.log
[09-Feb-2019 15:37:49 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:49 UTC] ### WORKER rune_SY_wrk.php STARTING... ###  
[09-Feb-2019 15:37:49 UTC] ### INITIALIZE ENVIRONMENT --- ###  
[09-Feb-2019 15:37:49 UTC] ### wrk_getHwPlatform() /proc/cpuinfo hardware ###  BCM2835
[09-Feb-2019 15:37:49 UTC] ### wrk_getHwPlatform() /proc/cpuinfo revision ###  a020d3
[09-Feb-2019 15:37:49 UTC] ### detected architecture:  ###  08
[09-Feb-2019 15:37:49 UTC] ### sysCmd($str) ###  cd /var/www/ ; git branch | grep "*" | cut -d ' ' -f 2
[09-Feb-2019 15:37:49 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:49 UTC] ### sysCmd() output: ###  ['0'] => 0.5b
[09-Feb-2019 15:37:49 UTC] ### GIT BRANCH:  ###  0.5b
[09-Feb-2019 15:37:49 UTC] ### >>>>>>MPD VERSION HAS CHANGED PROCESS --- ###  
[09-Feb-2019 15:37:50 UTC] ### sysCmd($str) ###  chown -R http.http /srv/http/
[09-Feb-2019 15:37:50 UTC] ### sysCmd() output: ### $data type = array

[09-Feb-2019 15:37:56 UTC] ### sysCmd($str) ###  find /srv/http/ -type f -exec chmod 644 {} \;
[09-Feb-2019 15:37:56 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:57 UTC] ### sysCmd($str) ###  find /srv/http/ -type d -exec chmod 755 {} \;
[09-Feb-2019 15:37:57 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  find /etc -name *.conf -exec chmod 644 {} \;
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  find /usr/lib/systemd/system -name *.service -exec chmod 644 {} \;
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 644 /etc/nginx/html/50x.html
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 777 /run
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 755 /srv/http/command/*
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 755 /srv/http/db/redis_datastore_setup
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 755 /srv/http/db/redis_acards_details
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 755 /etc/X11/xinit/start_chromium.sh
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chown mpd.audio /mnt/MPD/*
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chown mpd.audio /mnt/MPD/USB/*
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ###  ['0'] => chown: cannot access '/mnt/MPD/USB/*': No such file or directory
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 777 /mnt/MPD/USB
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chmod 777 /mnt/MPD/USB/*
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ###  ['0'] => chmod: cannot access '/mnt/MPD/USB/*': No such file or directory
[09-Feb-2019 15:37:58 UTC] ### sysCmd($str) ###  chown -R mpd.audio /var/lib/mpd
[09-Feb-2019 15:37:58 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:58 UTC] ### invoke Redis player datastore check ###  
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  /var/www/db/redis_datastore_setup check
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ###  ['0'] => 
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ###  ['1'] => Warning: socket_connect(): unable to connect [111]: Connection refused in /srv/http/app/libs/runeaudio.php on line 58
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  mpc status | grep '^\[' | cut -d '[' -f 2 | cut -d ']' -f 1
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  mpc status | grep '^\[' | cut -d '#' -f 2 | cut -d '/' -f 1
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### wrk_mpdPlaybackStatus (current state): ###  stopped
[09-Feb-2019 15:37:59 UTC] ### wrk_mpdPlaybackStatus (current number): ###  
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  mpc volume
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  mpc stop
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  mpc volume 100
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:37:59 UTC] ### sysCmd($str) ###  mpc volume
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:37:59 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:38:00 UTC] ### sysCmd($str) ###  mpd --kill
[09-Feb-2019 15:38:00 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:00 UTC] ### sysCmd() output: ###  ['0'] => config_file: config parameter "id3v1_encoding" on line 25 is deprecated
[09-Feb-2019 15:38:00 UTC] ### sysCmd() output: ###  ['1'] => config_file: config parameter "buffer_before_play" on line 28 is deprecated
[09-Feb-2019 15:38:00 UTC] ### sysCmd() output: ###  ['2'] => config_file: config parameter "gapless_mp3_playback" on line 29 is deprecated
[09-Feb-2019 15:38:00 UTC] ### sysCmd() output: ###  ['3'] => exception: unable to read the pid from file "/var/run/mpd/pid": No such file or directory
[09-Feb-2019 15:38:01 UTC] ### sysCmd($str) ###  systemctl stop mpd ashuffle mpdscribble upmpdcli
[09-Feb-2019 15:38:01 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:01 UTC] ### reset mpdconf to defaults ###  
[09-Feb-2019 15:38:02 UTC] ### sysCmd($str) ###  mpd --version | grep -o 'Music Player Daemon.*' | cut -f4- -d' '
[09-Feb-2019 15:38:02 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:02 UTC] ### sysCmd() output: ###  ['0'] => 0.21.4 (0.21.4)
[09-Feb-2019 15:38:02 UTC] ### sysCmd($str) ###  /srv/http/db/redis_datastore_setup mpdreset
[09-Feb-2019 15:38:02 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:02 UTC] ### sysCmd() output: ###  ['0'] => 
[09-Feb-2019 15:38:02 UTC] ### sysCmd() output: ###  ['1'] => Warning: socket_connect(): unable to connect [111]: Connection refused in /srv/http/app/libs/runeaudio.php on line 58
[09-Feb-2019 15:38:03 UTC] ### sysCmd($str) ###  mpd --version | grep -c "soxr"
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ###  ['0'] => 1
[09-Feb-2019 15:38:03 UTC] ### force audio output ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  /boot/config.txt
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###  dtparam=audio=
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  dtparam=audio=on
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  ## RuneAudio HDMI & 3,5mm jack
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  1
[09-Feb-2019 15:38:03 UTC] ### line index match! $line ###  48
[09-Feb-2019 15:38:03 UTC] ### internal loop $line ###  dtparam=audio=on

[09-Feb-2019 15:38:03 UTC] [wrk_mpdconf] ### detected ACARDS  ### $data type = array
[09-Feb-2019 15:38:03 UTC] ### mpd.conf advanced state ###  0
[09-Feb-2019 15:38:03 UTC] ### sysCmd($str) ###  rm -f /tmp/mpd.conf
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard details      :  ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard name         :  ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard type         :  ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard device       :  ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard mixer_device :  ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard mixer_control:  ###  PCM
[09-Feb-2019 15:38:03 UTC] ### wrk_shairport acard extlabel     :  ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  /etc/shairport-sync.conf
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   general_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  name="RuneAudio"; // general_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  name="RuneAudio"; // general_name

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   general_output_backend
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  output_backend="alsa"; // general_output_backend
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  output_backend="alsa"; // general_output_backend

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   general_interpolation
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  // interpolation=""; // general_interpolation
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  // interpolation=""; // general_interpolation

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   general_alac_decoder
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  alac_decoder="apple"; // general_alac_decoder
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  alac_decoder="apple"; // general_alac_decoder

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   run_this_before_play_begins
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  run_this_before_play_begins="/var/www/command/airplay_toggle on"; // run_this_before_play_begins
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  run_this_before_play_begins="/var/www/command/airplay_toggle on"; // run_this_before_play_begins

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   run_this_after_play_ends
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  run_this_after_play_ends="/var/www/command/airplay_toggle off"; // run_this_after_play_ends
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  run_this_after_play_ends="/var/www/command/airplay_toggle off"; // run_this_after_play_ends

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   run_this_wait_for_completion
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  wait_for_completion="yes"; // run_this_wait_for_completion
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  wait_for_completion="yes"; // run_this_wait_for_completion

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   alsa_output_device
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  output_device=""; // alsa_output_device
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  output_device=""; // alsa_output_device

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   alsa_mixer_control_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  // mixer_control_name="PCM"; // alsa_mixer_control_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  // mixer_control_name="PCM"; // alsa_mixer_control_name

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   alsa_mixer_device
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  // mixer_device=""; // alsa_mixer_device
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  // mixer_device=""; // alsa_mixer_device

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   alsa_output_format
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  output_format="S16"; // alsa_output_format
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  output_format="S16"; // alsa_output_format

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   alsa_output_rate
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  output_rate="48100"; // alsa_output_rate
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  output_rate="48100"; // alsa_output_rate

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   pipe_pipe_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  name="/tmp/shairport-sync-output-pipe"; // pipe_pipe_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  name="/tmp/shairport-sync-output-pipe"; // pipe_pipe_name

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   metadata_enabled
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  enabled="yes"; // metadata_enabled
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  enabled="yes"; // metadata_enabled

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   metadata_include_cover_art
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  include_cover_art="yes"; // metadata_include_cover_art
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  include_cover_art="yes"; // metadata_include_cover_art

[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###   metadata_pipe_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  pipe_name="/tmp/shairport-sync-metadata"; // metadata_pipe_name
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  pipe_name="/tmp/shairport-sync-metadata"; // metadata_pipe_name

[09-Feb-2019 15:38:03 UTC] ### sysCmd($str) ###  rm -f /tmp/shairport-sync.conf
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine($file, $inputArray, $strfind, $strrepl, $linelabel, $lineoffset) ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $file ###  /etc/libao.conf
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strfind ###  dev=
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $strrepl ###  dev=
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $linelabel ###  
[09-Feb-2019 15:38:03 UTC] ### wrk_replaceTextLine $lineoffset ###  
[09-Feb-2019 15:38:03 UTC] ### replaceall $line ###  dev=

[09-Feb-2019 15:38:03 UTC] ### sysCmd($str) ###  rm -f /tmp/libao.conf
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:03 UTC] ### reset sourcecfg to defaults ###  
[09-Feb-2019 15:38:03 UTC] ### function wrk_sourcecfg(reset) ###  
[09-Feb-2019 15:38:03 UTC] ### sysCmd($str) ###  mpc stop
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:38:03 UTC] ### sysCmd($str) ###  systemctl stop mpd ashuffle
[09-Feb-2019 15:38:03 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:04 UTC] ### sysCmd($str) ###  systemctl start mpd
[09-Feb-2019 15:38:04 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:04 UTC] ### sysCmd() output: ###  ['0'] => Job for mpd.service failed because the control process exited with error code.
[09-Feb-2019 15:38:04 UTC] ### sysCmd() output: ###  ['1'] => See "systemctl status mpd.service" and "journalctl -xe" for details.
[09-Feb-2019 15:38:04 UTC] [sysCmdAsync] ### sysCmdAsync($cmdstr) decoded ###  sleep 1 && rune_prio nice
[09-Feb-2019 15:38:04 UTC] [sysCmdAsync] ### sysCmdAsync($cmdstr) encoded ###  /var/www/command/cmd_async c2xlZXAgMSAmJiBydW5lX3ByaW8gbmljZQ==
[09-Feb-2019 15:38:04 UTC] [sysCmdAsync] ### sysCmdAsync() output: ### $data type = array
[09-Feb-2019 15:38:04 UTC] ### sysCmd($str) ###  systemctl is-active mpd
[09-Feb-2019 15:38:04 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:04 UTC] ### sysCmd() output: ###  ['0'] => failed
[09-Feb-2019 15:38:05 UTC] ### sysCmd($str) ###  systemctl start mpd
[09-Feb-2019 15:38:05 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:05 UTC] ### sysCmd() output: ###  ['0'] => Job for mpd.service failed because the control process exited with error code.
[09-Feb-2019 15:38:05 UTC] ### sysCmd() output: ###  ['1'] => See "systemctl status mpd.service" and "journalctl -xe" for details.
[09-Feb-2019 15:38:05 UTC] ### sysCmd($str) ###  mpc update
[09-Feb-2019 15:38:05 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:05 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:38:06 UTC] ### sysCmd($str) ###  mpc outputs | grep -c -i enabled
[09-Feb-2019 15:38:06 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:06 UTC] ### sysCmd() output: ###  ['0'] => 0
[09-Feb-2019 15:38:06 UTC] ### sysCmd($str) ###  mpc enable only 1
[09-Feb-2019 15:38:06 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:06 UTC] ### sysCmd() output: ###  ['0'] => mpd error: Connection refused
[09-Feb-2019 15:38:06 UTC] ### --- MPD VERSION HAS CHANGED PROCESS ###  
[09-Feb-2019 15:38:06 UTC] ### sysCmd($str) ###  systemctl daemon-reload
[09-Feb-2019 15:38:06 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:07 UTC] ### sysCmd($str) ###  chmod 777 /run
[09-Feb-2019 15:38:07 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:07 UTC] ### sysCmd($str) ###  rm -f /etc/sudoers.d/http
[09-Feb-2019 15:38:07 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:07 UTC] ### sysCmd($str) ###  rm -f /etc/sudoers.d/http-backup
[09-Feb-2019 15:38:07 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:07 UTC] ### sysCmd($str) ###  mpd --version | grep -o 'Music Player Daemon.*' | cut -f4- -d' '
[09-Feb-2019 15:38:07 UTC] ### sysCmd() output: ### $data type = array
[09-Feb-2019 15:38:07 UTC] ### sysCmd() output: ###  ['0'] => 0.21.4 (0.21.4)
[09-Feb-2019 15:38:07 UTC] ### registered architecture:  ###  08
[09-Feb-2019 15:38:07 UTC] ### registered playerid:  ###  084cb5090d8d921338f6f382653d66f2f6

```

This *is* looping.

**Comment by colinleroy** [comment]
(the $redis->close() is unnecessary though)

**Comment by janui** [comment]
Hi colinroy,
Thanks for your persistence in reporting this. Quite correct, my mistake. However your fix could cause problems in the future. The actual error is in /srv/http/app/libs/runeaudio.php, function wrk_mpdconf(), case 'reset'. The line 'sysCmd('/srv/http/db/redis_datastore_setup mpdreset');' must be run before resetting the MPD version number in '$redis->hSet('mpdconf', 'version', trim(reset($command)));'. At the moment the version is updated and then reset back to 0.20.20.
I will need to test this to doublecheck that it works. Will close this issue when I post a fix.
Thanks again,
janui

**Comment by janui** [comment]
See: 'Fix MPD update loop - Github issue: Two littles fixes #15', git pull to fix

**Comment by colinleroy** [comment]
Thank you Janui :)

**Pull request closed without merging**
